from __future__ import absolute_import,print_function

### This file is generated automatically.
### Any changes will be lost!!!
### Instead, modify deflector_generator.py


from abaqute.common.abaqus_imports import mdb,OFF,ON,THREE_D,DEFORMABLE_BODY,MIDDLE_SURFACE,FROM_SECTION,CARTESIAN,SOLVER_DEFAULT,\
	STEP,UNSET,UNIFORM,SINGLE,PERCENTAGE,DEFAULT,DOMAIN,ODB,ANALYSIS,RIGHT,CLOCKWISE,COUNTERCLOCKWISE,LEFT,WIRE,GLOBAL,HARD,SELF,\
	ISOTROPIC,PENALTY,FRACTION,SET,Region,MPI,MEDIAL_AXIS,HEX

mdb,OFF,ON,THREE_D,DEFORMABLE_BODY,MIDDLE_SURFACE,FROM_SECTION,CARTESIAN,SOLVER_DEFAULT,STEP,UNSET,UNIFORM,SINGLE,PERCENTAGE,DEFAULT,DOMAIN,ODB,ANALYSIS,RIGHT,CLOCKWISE,COUNTERCLOCKWISE,LEFT,WIRE,GLOBAL,HARD,SELF,ISOTROPIC,PENALTY,FRACTION,SET,Region,MPI,MEDIAL_AXIS,HEX=mdb,OFF,ON,THREE_D,DEFORMABLE_BODY,MIDDLE_SURFACE,FROM_SECTION,CARTESIAN,SOLVER_DEFAULT,STEP,UNSET,UNIFORM,SINGLE,PERCENTAGE,DEFAULT,DOMAIN,ODB,ANALYSIS,RIGHT,CLOCKWISE,COUNTERCLOCKWISE,LEFT,WIRE,GLOBAL,HARD,SELF,ISOTROPIC,PENALTY,FRACTION,SET,Region,MPI,MEDIAL_AXIS,HEX
